docs_dir: doc/book/ru
pages:
    - index.md
    - 'Стратегия работы с ветками и тегами в git': 'git-workflow.md'
    - 'Архитектура':
      - 'Сервис-оринтированная архитектура': 'soa.md'
      - 'Сервисы': 'service.md'
      - 'Версионирование': 'version.md'
    - 'Сервисы':
      - 'Абстрактные сервисы': 'abstract-service.md'
      - 'Принципы построения доменной модели': 'service-domain-model.md'
    - 'Модули':
      - 'Как создавать модули': 'module-valid.md'
      - 'Конфигурирование модуля': 'module-configs.md'
site_name: nnx-framework-best-practices
site_description: 'Стандарты и подходы в разработке'
repo_url: 'https://github.com/nnx-framework/best-practices'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX-Group</a>'